title = "Neural Network, Haskell, and You"
subtitle = "On the surprising ergonomics of functional programming for machine learning" 
author = "Nico OR"
content_path = "assets/haskellNN/haskellNN.md"
link = "articles/haskellNN.html"
date = "2025-11-22"
