title = "Note on the Monad"
subtitle = "I promise it's not actually that difficult" 
author = "Nico OR"
content_path = "assets/monad/monad.md"
link = "articles/monad.html"
date = "2026-01-02"
hidden = true
